import React from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";

// 1️⃣ Styles
const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 12, fontFamily: "Helvetica" },
  title: { fontSize: 18, marginBottom: 10, textAlign: "center" },
  subtitle: { fontSize: 12, marginBottom: 20, textAlign: "center", color: "grey" },
  table: {
    display: "table",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    marginTop: 10,
  },
  tableRow: { flexDirection: "row" },
  tableColHeader: {
    width: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    backgroundColor: "#f2f2f2",
    padding: 5,
    fontWeight: "bold",
  },
  tableCol: {
    width: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    padding: 5,
  },
  footer: {
    marginTop: 20,
    fontSize: 10,
    textAlign: "right",
    color: "grey",
  },
});

// 2️⃣ PDF Document
const ReportDocument = ({ records }) => {
  const newPatients = records.filter(r => r.firstVisitDate === r.lastVisitDate);
  const returningPatients = records.filter(r => r.firstVisitDate !== r.lastVisitDate);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>New vs Returning Patients Report</Text>
        <Text style={styles.subtitle}>
          Generated on: {new Date().toLocaleDateString()}
        </Text>

        <View style={styles.table}>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Category</Text>
            <Text style={styles.tableColHeader}>Count</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableCol}>New Patients</Text>
            <Text style={styles.tableCol}>{newPatients.length}</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableCol}>Returning Patients</Text>
            <Text style={styles.tableCol}>{returningPatients.length}</Text>
          </View>
        </View>

        <Text style={styles.footer}>OPDMS Report • Generated by System</Text>
      </Page>
    </Document>
  );
};

export default ReportDocument;